import { SeasonData } from './type'

export const data: SeasonData = {
  1: {
    number: 1,
    name: 'Wild Frontier',
    start: '',
    split: '',
    end: '',
  },
  2: {
    number: 2,
    name: 'Battle Charge',
    start: '',
    split: '',
    end: '',
  },
  3: {
    number: 3,
    name: 'Meltdown',
    start: '',
    split: '',
    end: '',
  },
  4: {
    number: 4,
    name: 'Assimilation',
    start: '',
    split: '',
    end: '',
  },
  5: {
    number: 5,
    name: 'Fortune’s Favor',
    start: '',
    split: '',
    end: '',
  },
  6: {
    number: 6,
    name: 'Boosted',
    start: '',
    split: '',
    end: '',
  },
  7: {
    number: 7,
    name: 'Ascension',
    start: '',
    split: '',
    end: '',
  },
  8: {
    number: 8,
    name: 'Mayhem',
    start: '',
    split: '',
    end: '',
  },
  9: {
    number: 9,
    name: 'Legacy',
    start: '',
    split: '',
    end: '',
  },
  10: {
    number: 10,
    name: 'Emergence',
    start: '',
    split: '',
    end: '',
  },
  11: {
    number: 11,
    name: 'Escape',
    start: '',
    split: '',
    end: '',
  },
  12: {
    number: 12,
    name: 'Defiance',
    start: '',
    split: '',
    end: '',
  },
  13: {
    number: 13,
    name: 'Saviors',
    start: '',
    split: '',
    end: '',
  },
  14: {
    number: 14,
    name: 'Hunted',
    start: '',
    split: '',
    end: '',
  },
  15: {
    number: 15,
    name: 'Eclipse',
    start: '2022-11-01T17:00:00Z',
    split: '2023-01-18T17:00:00Z',
    end: '2023-02-14T17:00:00Z',
  },
  16: {
    number: 16,
    name: 'Revelry',
    start: '2023-02-14T17:00:00Z',
    split: '2023-04-05T17:00:00Z',
    end: '2023-05-14T17:00:00Z',
  },
}
